## 1. Numpy
- Python에서 수학적인 계산(행렬, 벡터, 차원)을 편하게 할 수 있도록 돕는 라이브러리

In [2]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [8]:
# 1차원 배열
arr1 = np.array([1,2,3])

arr1
type(arr1)
arr1.shape # 1행 3열
arr1.ndim # 1차원

1

In [12]:
# 2차원 배열
arr2 = np.array([[1,2,3], [1,2,3]])

arr2
type(arr2)
arr2.shape # 2행 3열
arr2.ndim # 2차원

2

In [13]:
# ndarray 데이터 타입

arr3 = [1,2,'c']

arr3 = np.array(arr3)
arr3.dtype

dtype('<U11')

In [14]:
# ndarray 생성

arr = np.arange(10)

arr > 5 # bollean indexing

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.zeros((3, 2))
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
# reshape -> 차원을 변경
arr = np.arange(10)

arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
# indexing & slicing
arr[0]
arr[0:5]

array([0, 1, 2, 3, 4])

## Numpy 예제 풀기

Q1. 2차원 배열에서 행렬의 각 행 평균을 계산하는 코드를 작성하세요.

np.mean() == 평균 계산

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [8]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

arr.shape # 3행 3열

print(arr)

# axis=0(열), axis=1(행), axis=2(채널)
np.mean(arr, axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2., 5., 8.])

Q2. 1차원 배열에서 짝수 인덱스의 값을 출력하는 코드를 작성하세요.

arr = np.array([1,2,3,4,5,6])

In [11]:
arr = np.array([1,2,3,4,5,6])

even_indexes = np.arange(0, arr.size, 2)

print(arr[even_indexes])
# 눈으로 보이는 숫자로는 2, 4, 6이 나와야겠지만 인덱싱의 시작값은 0부터 시작하기에 (0,1,2,3,4,5) 표출되는 값은 1, 3, 5가 나오는 것이 맞다.

[1 3 5]


Q3. 2차원 배열의 주 대각선 상에 있는 원소들을 출력하는 코드를 작성하세요.

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [14]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

arr.shape

# diag를 이용한다.

np.diag(arr)

array([1, 5, 9])

Q4. 2차원 배열에서 각 열의 표준편차를 계산하는 코드를 작성하세요.

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

- 표준 편차란?
    
    → 통계집단의 [분산](https://ko.wikipedia.org/wiki/%EB%B6%84%EC%82%B0)의 정도 또는 자료의 [산포도](https://ko.wikipedia.org/wiki/%EC%82%B0%ED%8F%AC%EB%8F%84)를 나타내는 수치로, [분산](https://ko.wikipedia.org/wiki/%EB%B6%84%EC%82%B0)의 음이 아닌 [제곱근](https://ko.wikipedia.org/wiki/%EC%A0%9C%EA%B3%B1%EA%B7%BC) 즉, **분산을 제곱근한 것**

In [16]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

np.std(arr) # 이건 전체 표준편차를 구하는 코드다

print(arr)

np.std(arr, axis=0) # 각 열의 표준편차를 구하려면 axis를 이용해야 한다.

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2.44948974, 2.44948974, 2.44948974])

Q5. 1차원 배열에서 중앙값(median)을 계산하는 코드를 작성하세요.

arr = np.array([1,2,3,4,5])

In [17]:
arr = np.array([1,2,3,4,5])
np.median(arr)

3.0

Q6. 1차원 배열에서 원소의 값이 5 이상인 것들만 출력하는 코드를 작성하세요.

arr = np.array([1,4,6,3,9,2,7,8])

In [20]:
arr = np.array([1,4,6,3,9,2,7,8])

arr >= 5 # 이걸로 실행을 하면 boolean indexing이 되어 False와 True 값이 출력된다.

arr[arr >= 5] # 응용해서 이걸로 실행하면 대괄호 안에서 True의 값을 가진 것들만 출력된다.

array([6, 9, 7, 8])

Q7. 1차원 배열에서 원소의 값이 3 또는 5인 것들의 인덱스를 출력하는 코드를 작성하세요.

arr = np.array([1,3,5,2,4,6,3,5,7])

In [26]:
arr = np.array([1,3,5,2,4,6,3,5,7])

np.where((arr == 3) | (arr == 5)) # and는 &으로, or는 | (백스페이스 바로 아래키를 shift 누르고)

(array([1, 2, 6, 7], dtype=int64),)

https://github.com/scikit-learn/scikit-learn/blob/9aaed498795f68e5956ea762fef9c440ca9eb239/sklearn/gaussian_process/kernels.py